# Generated by Django 6.1 on 2026-09-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinigod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintura',
            name='nro_pintura',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
